Repository Team-Taskify/Taskify-Web, pull requests merged in 2024-02, with the labels that each got.

#92 86 페이지회원가입 페이지 구현
  taskify-web/src/components/auth/feature-signup-form/SignUpForm.module.scss
  taskify-web/src/components/auth/feature-signup-form/SignUpForm.tsx
  taskify-web/src/components/auth/feature-signup-form/constant.ts
  taskify-web/src/components/auth/ui-auth-footer/AuthFooter.tsx
  taskify-web/src/components/auth/ui-auth-header/AuthHeader.tsx
  taskify-web/src/contexts/AuthProvider.tsx
  taskify-web/src/pages/signin.tsx
  taskify-web/src/pages/signup.tsx
  taskify-web/src/types/auth.ts
Labels: enhancement

#93 Feat80 서브헤더 수정
  taskify-web/src/components/commons/ui-dropdown/Dropdown.module.scss
  taskify-web/src/components/commons/ui-profile-Label/ProfileLabel.module.scss
  taskify-web/src/components/commons/ui-profile-Label/ProfileLabel.tsx
  taskify-web/src/components/commons/ui-sub-header/DashboardName.module.scss
  taskify-web/src/components/commons/ui-sub-header/DashboardName.tsx
  taskify-web/src/components/commons/ui-sub-header/DashboardSubHeader.tsx
  taskify-web/src/components/commons/ui-sub-header/DashboardUserList.module.scss
  taskify-web/src/components/commons/ui-sub-header/DashboardUserList.tsx
  taskify-web/src/components/commons/ui-sub-header/SubHeaderButton.module.scss
  taskify-web/src/components/commons/ui-sub-header/SubHeaderButton.tsx
  taskify-web/src/components/commons/ui-sub-header/SubHeaderItemsLeft.module.scss
  taskify-web/src/components/commons/ui-sub-header/SubHeaderItemsRight.module.scss
  taskify-web/src/components/commons/ui-sub-header/constant.ts
  taskify-web/src/components/commons/ui-sub-header/utils/getRandomColor.ts
  taskify-web/src/components/commons/ui-sub-header/utils/getRemainNumber.ts
  taskify-web/src/components/commons/ui-sub-header/utils/getWindowSize.ts
  taskify-web/src/components/commons/ui-user-badge/UserBadge.module.scss
  taskify-web/src/components/commons/ui-user-badge/UserBadge.tsx
Labels: enhancement

#99 Feat84 카드 카드 기본 틀 구현
  taskify-web/src/components/commons/ui-card/Card.module.scss
  taskify-web/src/components/commons/ui-card/Card.tsx
  taskify-web/src/components/commons/ui-card/calendar.svg
Labels: enhancement

#98 feat95 dashboard관련 페이지 레이아웃 구현
  taskify-web/src/components/commons/ui-main-header/.gitkeep
  taskify-web/src/components/commons/ui-main-header/MainHeader.module.scss
  taskify-web/src/components/commons/ui-main-header/MainHeader.tsx
  taskify-web/src/components/commons/ui-pagination/PaginationButton.module.scss
  taskify-web/src/components/commons/ui-pagination/PaginationButton.tsx
  taskify-web/src/components/commons/ui-pagination/PaginationButtonContainer.tsx
  taskify-web/src/components/commons/ui-pagination/arrow.svg
  taskify-web/src/components/commons/ui-sidebar/Sidebar.tsx
  taskify-web/src/components/dashboard/feat-side-bar/SideBar.tsx
  taskify-web/src/components/dashboard/feat-sub-header/SubHeader.tsx
  taskify-web/src/components/page-layout/dashboard-layout/DashBoardLayout.module.scss
  taskify-web/src/components/page-layout/dashboard-layout/DashBoardLayout.tsx
  taskify-web/src/contexts/SidebarProvider.tsx
  taskify-web/src/pages/_app.tsx
Labels: enhancement

#96 Feat94 유저 뱃지 컴포넌트 사이즈 변경 기능 구현
  taskify-web/src/components/commons/ui-user-badge/UserBadge.module.scss
  taskify-web/src/components/commons/ui-user-badge/UserBadge.tsx
Labels: enhancement

#102 feat:100 이미지 파일 인풋 컴포넌트 구현
  taskify-web/next.config.mjs
  taskify-web/src/components/commons/ui-image-input/ImageInput.module.scss
  taskify-web/src/components/commons/ui-image-input/ImageInput.tsx
  taskify-web/src/components/commons/ui-main-header/.gitkeep
Labels: enhancement

#107 Feat103 폼 검색 인풋 추가
  taskify-web/package-lock.json
  taskify-web/package.json
  taskify-web/src/components/commons/feat-search-input/SearchInput.module.scss
  taskify-web/src/components/commons/feat-search-input/SearchInput.tsx
  taskify-web/src/components/commons/feat-search-input/search.svg
  taskify-web/src/components/commons/ui-input/Input.tsx
Labels: enhancement

#109 Feat108 버튼 대시보드 진입 버튼 구현
  taskify-web/src/components/dashboard/ui-dashboard-enter-button/DashboardEnterButton.module.scss
  taskify-web/src/components/dashboard/ui-dashboard-enter-button/DashboardEnterButton.tsx
  taskify-web/src/components/dashboard/ui-dashboard-enter-button/arrow.svg
Labels: enhancement

#110 feat:104 mypage 메인 컴포넌트 구현
  taskify-web/src/components/commons/ui-image-input/ImageInput.module.scss
  taskify-web/src/components/commons/ui-input/Input.module.scss
  taskify-web/src/components/commons/ui-input/Input.tsx
  taskify-web/src/components/commons/ui-profile-Label/ProfileLabel.tsx
  taskify-web/src/components/commons/ui-sub-header/DashboardUserList.tsx
  taskify-web/src/components/commons/ui-user-badge/UserBadge.tsx
  taskify-web/src/components/dashboard/feat-change-password-form/ChangePasswordForm.module.scss
  taskify-web/src/components/dashboard/feat-change-password-form/ChangePasswordForm.tsx
  taskify-web/src/components/dashboard/feat-change-password-form/constant.ts
  taskify-web/src/components/dashboard/feat-change-profile-form/ChangeProfileForm.module.scss
  taskify-web/src/components/dashboard/feat-change-profile-form/ChangeProfileForm.tsx
  taskify-web/src/components/dashboard/feat-change-profile-form/constant.ts
  taskify-web/src/components/dashboard/ui-go-back-main/GoBackMain.module.scss
  taskify-web/src/components/dashboard/ui-go-back-main/GoBackMain.tsx
  taskify-web/src/components/dashboard/ui-go-back-main/arrow-back.svg
  taskify-web/src/components/page-layout/dashboard-layout/DashBoardLayout.module.scss
  taskify-web/src/contexts/AuthProvider.tsx
  taskify-web/src/contexts/SidebarProvider.tsx
  taskify-web/src/pages/mypage.tsx
  taskify-web/src/types/auth.ts
Labels: enhancement

#114 Feat97 담당자상태 드롭다운 구현
  taskify-web/src/components/commons/ui-profile-Label/ProfileLabel.module.scss
  taskify-web/src/components/commons/ui-profile-Label/ProfileLabel.tsx
  taskify-web/src/components/commons/ui-user-state-dropdown/UserStateDropdown.module.scss
  taskify-web/src/components/commons/ui-user-state-dropdown/UserStateDropdown.tsx
  taskify-web/src/components/commons/ui-user-state-dropdown/arrow.svg
  taskify-web/src/components/commons/ui-user-state-dropdown/check.svg
  taskify-web/src/components/commons/ui-user-state-dropdown/constant.ts
  taskify-web/src/components/commons/ui-user-state-dropdown/types.ts
Labels: enhancement

#122 feat120 mypage 비밀번호 오류 모달로 변경 및 edit 페이지 테이블 제외 구성
  taskify-web/src/components/auth/ui-auth-modal/AuthModal.tsx
  taskify-web/src/components/commons/ui-color-chip/ColorChip.module.scss
  taskify-web/src/components/commons/ui-color-chip/ColorChip.tsx
  taskify-web/src/components/commons/ui-color-chip/ColorChipList.module.scss
  taskify-web/src/components/commons/ui-color-chip/ColorChipList.tsx
  taskify-web/src/components/commons/ui-sub-header/DashboardUserList.module.scss
  taskify-web/src/components/commons/ui-sub-header/DashboardUserList.tsx
  taskify-web/src/components/commons/ui-sub-header/SubHeaderButton.tsx
  taskify-web/src/components/commons/ui-sub-header/utils/getRemainNumber.ts
  taskify-web/src/components/dashboard/feat-add-dashboard-modal/AddDashboardModal.module.scss
  taskify-web/src/components/dashboard/feat-add-dashboard-modal/AddDashboardModal.tsx
  taskify-web/src/components/dashboard/feat-change-dashboard-form/ChangeDashBoardForm.module.scss
  taskify-web/src/components/dashboard/feat-change-dashboard-form/ChangeDashBoardForm.tsx
  taskify-web/src/components/dashboard/feat-change-password-form/ChangePasswordForm.tsx
  taskify-web/src/components/dashboard/feat-side-bar/SideBar.tsx
  taskify-web/src/contexts/AuthProvider.tsx
  taskify-web/src/contexts/DashBoardProvider.tsx
  taskify-web/src/lib/hooks/useGetDashboards.ts
  taskify-web/src/lib/hooks/useGetMembers.ts
  taskify-web/src/pages/_app.tsx
  taskify-web/src/pages/dashboard/[boardId]/edit.tsx
  taskify-web/src/pages/dashboard/[boardId]/index.tsx
  taskify-web/src/pages/mypage.tsx
  taskify-web/src/types/dashboard.ts
Labels: enhancement

#130 feat:124 edit 페이지 끝내기
  taskify-web/src/components/commons/ui-button/Button.module.scss
  taskify-web/src/components/commons/ui-delete-dashboard-button/DeleteDashBoardButton.module.scss
  taskify-web/src/components/commons/ui-pagination/PaginationButton.module.scss
  taskify-web/src/components/commons/ui-pagination/PaginationButton.tsx
  taskify-web/src/components/commons/ui-pagination/PaginationButtonContainer.tsx
  taskify-web/src/components/commons/ui-sub-header/DashboardUserList.tsx
  taskify-web/src/components/commons/ui-sub-header/SubHeaderButton.tsx
  taskify-web/src/components/dashboard/feat-invite-modal/InviteModal.module.scss
  taskify-web/src/components/dashboard/feat-invite-modal/InviteModal.tsx
  taskify-web/src/components/dashboard/feat-invite-status-list/InviteStatusList.module.scss
  taskify-web/src/components/dashboard/feat-invite-status-list/InviteStatusList.tsx
  taskify-web/src/components/dashboard/feat-invite-status-list/InviteStatusListItem.module.scss
  taskify-web/src/components/dashboard/feat-invite-status-list/InviteStatusListItem.tsx
  taskify-web/src/components/dashboard/feat-invite-status-list/add-box.svg
  taskify-web/src/components/dashboard/feat-member-list/MemberList.module.scss
  taskify-web/src/components/dashboard/feat-member-list/MemberList.tsx
  taskify-web/src/components/dashboard/feat-member-list/MemberListItem.module.scss
  taskify-web/src/components/dashboard/feat-member-list/MemberListItem.tsx
  taskify-web/src/contexts/DashBoardProvider.tsx
  taskify-web/src/contexts/MemberProvider.tsx
  taskify-web/src/lib/hooks/useGetMembers.ts
  taskify-web/src/pages/dashboard/[boardId]/edit.tsx
  taskify-web/src/types/dashboard.ts
Labels: enhancement

#127 Feat117 할일 생성 / 수정 모달 구현
  taskify-web/src/components/commons/feat-create-card-modal/CreateCardModal.module.scss
  taskify-web/src/components/commons/feat-create-card-modal/CreateCardModal.tsx
  taskify-web/src/components/commons/feat-create-card-modal/MockData.ts
  taskify-web/src/components/commons/feat-create-card-modal/type.ts
  taskify-web/src/components/commons/ui-calendar-input/Calendar.module.scss
  taskify-web/src/components/commons/ui-chip-subject/chipSubject.module.scss
  taskify-web/src/components/commons/ui-chip-subject/chipSubject.tsx
  taskify-web/src/components/commons/ui-chip-subject/getChipRandomColor.ts
  taskify-web/src/components/commons/ui-profile-Label/ProfileLabel.tsx
  taskify-web/src/components/commons/ui-progress-chip/ProgressChip.tsx
  taskify-web/src/components/commons/ui-tag-input/TagInput.module.scss
  taskify-web/src/components/commons/ui-tag-input/TagInput.tsx
  taskify-web/src/components/commons/ui-user-badge/UserBadge.tsx
  taskify-web/src/components/commons/ui-user-state-dropdown/UserStateDropdown.module.scss
  taskify-web/src/components/commons/ui-user-state-dropdown/UserStateDropdown.tsx
  taskify-web/src/components/commons/ui-user-state-dropdown/types.ts
  taskify-web/src/styles/global.scss
Labels: enhancement

#133 Feat131 대시보드 화면 디자인 구현
  taskify-web/src/components/dashboard/ui-dashboard-form/DashboardForm.module.scss
  taskify-web/src/components/dashboard/ui-dashboard-form/DashboardForm.tsx
  taskify-web/src/components/dashboard/ui-dashboard-form/mock/mock.json
  taskify-web/src/components/dashboard/ui-dashboard-form/types.ts
  taskify-web/src/contexts/ColumnProvider.tsx
  taskify-web/src/pages/dashboard/[boardId]/index.tsx
  taskify-web/src/types/card.ts
  taskify-web/src/types/column.ts
Labels: enhancement

#138 fix:137 초대모달 오류수정
  taskify-web/src/components/dashboard/feat-invite-modal/InviteModal.tsx
  taskify-web/src/components/dashboard/feat-member-list/MemberList.tsx
  taskify-web/src/contexts/MemberProvider.tsx
Labels: bug, enhancement

#142 fix: 141 서브헤더 fixed 수정
  taskify-web/src/components/commons/ui-dashboard-info-label/DashboardInfoLabel.module.scss
  taskify-web/src/components/commons/ui-profile-Label/ProfileLabel.module.scss
  taskify-web/src/components/commons/ui-sidebar/Sidebar.module.scss
  taskify-web/src/components/commons/ui-sub-header/DashboardUserList.module.scss
  taskify-web/src/components/commons/ui-sub-header/DashboardUserList.tsx
  taskify-web/src/components/commons/ui-sub-header/SubHeader.module.scss
  taskify-web/src/components/dashboard/feat-sub-header/SubHeader.tsx
  taskify-web/src/components/page-layout/dashboard-layout/DashBoardLayout.module.scss
Labels: bug, enhancement

#144 Fix140 대시보드 대시보드 폼 hydration 및 기타 오류 수정
  taskify-web/src/components/commons/ui-card/Card.tsx
  taskify-web/src/components/dashboard/ui-dashboard-form/DashboardForm.tsx
Labels: bug

#150 Fix149 태그 칩 인풋 중복 태그 수정/ 생성 모달 데이터 초기화
  taskify-web/src/components/commons/feat-create-card-modal/CreateCardModal.tsx
  taskify-web/src/components/commons/ui-tag-input/TagInput.tsx
Labels: bug

#161 Feat152 대시보드 버튼 연결
  taskify-web/src/components/commons/ui-card-column/ColumnHeader.tsx
  taskify-web/src/components/commons/ui-card/Card.tsx
  taskify-web/src/components/dashboard/feat-column/DashboardCardColumn.tsx
  taskify-web/src/pages/dashboard/[boardId]/index.tsx
Labels: enhancement

#167 hotFix: "카드모달 setState를 prop으로 직접 전달하는 부분 콜백으로 변경"
  taskify-web/src/components/commons/feat-create-card-modal/CreateCardModal.tsx
  taskify-web/src/components/dashboard/feat-column/DashboardCardColumn.tsx
Labels: bug

#171 hotfix:170 hotfix 초기 로그인 시 대시보드목록 뜨지 않는 문제 수정
  taskify-web/src/components/dashboard/feat-sub-header/SubHeader.tsx
  taskify-web/src/contexts/AuthProvider.tsx
  taskify-web/src/contexts/DashBoardProvider.tsx
  taskify-web/src/contexts/MemberProvider.tsx
Labels: bug, enhancement

#174 Fix173 나의대시보드 대시보드생성 부분 렌더링오류수정
  taskify-web/src/components/dashboard/feat-add-dashboard-modal/AddDashboardModal.tsx
  taskify-web/src/components/dashboard/feat-my-dashboard-list/MydashboardList.tsx
Labels: bug

#178 Feat162 대시보드 새로운 칼럼 추가하기 클릭 시 칼럼 추가하기 모달 표시
  taskify-web/src/components/commons/ui-column-modal/ColumnModal.tsx
  taskify-web/src/components/dashboard/feat-column/DashboardCardColumn.tsx
  taskify-web/src/lib/hooks/useAsync.ts
Labels: enhancement

#180 feat: 카드 생성, 수정, 삭제 실시간 반영
  taskify-web/src/components/commons/feat-create-card-modal/CreateCardModal.tsx
  taskify-web/src/components/commons/ui-management-modal/ManagementModal.tsx
  taskify-web/src/components/dashboard/feat-column/DashboardCardColumn.tsx
Labels: bug, enhancement

#182 fix: "대시보드 변경시 칼럼도 함께 변경"
  taskify-web/src/contexts/ColumnProvider.tsx
Labels: bug

#189 Hotfix183 hotfix 대시보드 칼럼 추가 실시간 반영
  taskify-web/src/components/commons/feat-create-column-modal/CreateColumnModal.tsx
  taskify-web/src/components/dashboard/feat-column/DashboardCardColumn.tsx
  taskify-web/src/contexts/ColumnProvider.tsx
Labels: bug, enhancement
